//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiddharthJasapara_550.Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
        public string type { get; set; }
        public Nullable<int> productId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
